language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.0
    - 7.1
    - 7.2

matrix:
    include:
        - env: BUILD_TYPE=doc # marker environment variable to make the build matrix more readable in the UI
          php: none # unused by the python language but allows to clean the display of the matrix
          # Override the different steps of the build config
          language: python
          before_install: []
          install: pip install Sphinx sphinx_rtd_theme
          before_script: []
          script: sphinx-build -nW -b html -d docs/build/doctrees docs docs/build/html
          after_script: []
        - php: 7.1
          dist: precise

env:
    global:
        - BUILD_TYPE=code
        - secure: HhIy0kN0+UbuLeaVBk7O/utAYo038a9Emr8cdcfU+LQTu6CfGEbifH+LddXs6M/bSLTdNUSwQSnwycbeNYZ6iHCO/JI/vEgKxCTSecPerMXBIVCQjFZaCp3Tev8JJ40hKe78WJ/d0G4bGtIR6atR5V+H8Z29iwJeFtCj6doEt3o=
        - secure: oLadQTqg8HSEmUC0qEtChKd/R0ZiFNhzoZjIaa8kAJ0fjln/2xfNCBQIg4YstyjFy2kLiP6Lg8xW/RZljzyTHC+MCB9NNqTYjKLqFNRvFOlZUOnrAwc4sl4qjMYu9klWKa+rfyZzsuVWn++g829s2lFopkImqa6EB9DOR2TOT6w=
        - secure: Tsh/Vvb9auy672eRf0xbN8fKDr8OYzjRkZDHiaYc5yH49UkoromwPaC74mJtM5KxFOYalrC+GzwOSuvzT8RYO/XwTuk6IGw9P/0v0qMCaSLkjaRzerwVH1L3RPgDokqDnCHAgSzkAlg8d5o0MWBlbxaYiaKL4LmEKGwxQjrW590=
        - secure: HQQ1FY27tpn0Idy+NDYXdbnMjHKIOsZoE59qYfs18euS0zM559gcuMk4OQ/J2lcDFmdb6vjSFlznwH+6iVyoLuC5WAP3JGQ3UXSJ+7huRV/eDI6WepmEymjEOSWvTT+RYpmQu1lQWC2Y3zBCVbVT7sbVsqXvmuR2daBL11dpU+g=

install:
    - composer update phpunit/phpunit --with-dependencies
    - composer require satooshi/php-coveralls:^1.0 --dev

before_script:
    - mkdir -p build/logs

script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi;
    - if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then vendor/bin/phpunit; fi;

after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar -t 3; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;
